version: '3'
services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
  www:
    build: .
    environment:
      NODE_ENV: docker
    links:
      - db
    ports:
      - "5000:5000"

